### ISSUE TITLE
Submit all documents to David

### ISSUE THREAD

**Issue by bobrown101** [GE-MDS-FNM-V2/GE-MDS-FNM-V2#14]
Domain Model
Final project plan

**Comment by davidchristine88** [comment]
Here are my comments and question for the Domain Model, we can go over today...
1.	Field Network Manager also gets events notification from MDS Radios (perhaps add an Events Publisher box under MDS Radios and a notification arrow route back to FNM)
2.	Field Network Manager is “Hosted on” and “Installed on” Operating System.   Maybe you can combine Computer and Operating System together or use parent-child relationship.   Since Computer/OS uses Physical resources also…
3.	I would model your Wireless and Ethernet differently.   We only use IP connectivity (ex: UDP/TCP), so maybe just use the 2 logical IP and Serial devices boxes.   I think adding the physical boxes are kind of making the model a little confusing.
4.	I am not sure what the RTU try to represent?   Another communication protocol?

Thanks,
David
